pkey: fix compilation with OpenSSL 4.1
Avoid deprecated OpenSSL functions, add fallback defines for older
versions:
src/tpm2-provider-pkey.c:91:5: error: 'ASN1_STRING_set' is deprecated:
Since OpenSSL 4.1; use ASN1_STRING_set1_data() or ASN1_STRING_set1_string()
[-Werror,-Wdeprecated-declarations]
src/tpm2-provider-pkey.c:165:41: error: 'ASN1_STRING_length' is deprecated:
Since OpenSSL 4.1; use ASN1_STRING_get_length()
[-Werror,-Wdeprecated-declarations]

Add missing header:
src/tpm2-provider-pkey.c:32:1: error: call to undeclared function 'ERR_raise';
ISO C99 and later do not support implicit function declarations
[-Wimplicit-function-declaration]

Signed-off-by: Moritz Buhl <moritz.buhl@infineon.com>